spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 000802
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: xxxx
            client-secret: xxxx
            redirect-uri: http://localhost:10000/user/oauth2/github/callback
            scope: read:user,user:email
          google:
            client-id: xxxx
            client-secret: xxxx
            redirect-uri: http://localhost:10000/user/oauth2/google/callback
            authorization-grant-type: code
            scope: profile, email, openid
          facebook:
            client-id: 123456789012345
            client-secret: abcdefghijklmnopqrstuvwxyz
            redirect-uri: http://localhost:10000/user/oauth2/facebook/callback
            authorization-grant-type: code
            scope: public_profile, email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  port: 10000
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
leaf:
  name: user
  segment:
    enable: true
    url: jdbc:mysql://localhost:3306/id?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 000802
# 限流配置
ratelimit:
  enabled: true  # 是否启用限流功能
  key-prefix: "zing:"  # 所有限流key的前缀
  expire-after-access: 1  # 限流器缓存过期时间（小时）
  global-rate-factor: 1.0 # 全局速率因子，可以统一调整所有限流的速率
  ip-based-enabled: true  # 是否启用IP限流
  user-based-enabled: true  # 是否启用用户限流
  provider: guava

# 三方登录配置
